---
title: "HW4_tidy2"
author: "Jake Ayala"
date: "7/16/2019"
output: html_document
---

```{r}

library(dplyr)

```

```{r}

train.x <- read.table(file = "~/Desktop/Tools and Techniques/UCI HAR Dataset/train/X_train.txt")
test.x <- read.table(file = "~/Desktop/Tools and Techniques/UCI HAR Dataset/test/X_test.txt")

train.y <- read.table(file = "~/Desktop/Tools and Techniques/UCI HAR Dataset/train/Y_train.txt")
test.y <- read.table(file = "~/Desktop/Tools and Techniques/UCI HAR Dataset/test/Y_test.txt")

train.sub <- read.table(file = "~/Desktop/Tools and Techniques/UCI HAR Dataset/train/subject_train.txt")
test.sub <- read.table(file = "~/Desktop/Tools and Techniques/UCI HAR Dataset/test/subject_test.txt")


```


```{r}

# We first combine the individual test and training sets. Then we column bind both the training and the test sets to the subject data frame.

x <- rbind(train.x, test.x)
y <- rbind(train.y, test.y)
subject <- rbind(train.sub, test.sub)

data1 <- cbind(y, x)
data <- cbind(subject, data1)

dim(data)

```

```{r}

# read features file
features <- read.table("~/Desktop/Tools and Techniques/UCI HAR Dataset/features.txt")

# rename columns
names(data) <- c("SubjectID", "ActivityName", as.character(features$V2))

str(features)

```


```{r}

# extract only mean and std features
sub.sd.mean <- features$V2[grep("-mean\\(\\)|-std\\(\\)", features[, 2])]

selColumns <- c("SubjectID", "ActivityName", as.character(sub.sd.mean))

# subset data to include only selected colunms
data <- subset(data, select = selColumns)


```

```{r}

# We use the following code to find and give descriptive names to the columns in the dataset using the gsub command. We then write the data set into “tidy_data.txt”

activity <- read.table("./UCI HAR Dataset/activity_labels.txt")
activity$V2 <- as.character(activity$V2)
data$ActivityName = activity[data$ActivityName, 2]
rm(activity, feature)

names(data) <- gsub("^t", "Time", names(data))
names(data) <- gsub("^f", "Frequency", names(data))
names(data) <- gsub("Acc", "Accelerometer", names(data))
names(data) <- gsub("Gyro", "Gyroscope", names(data))
names(data) <- gsub("Mag", "Magnitude", names(data))
write.table(data, "tidy_data.txt")

str(data)


```

```{r}

# We then group the tidy data by subject ID and Activity Name and we calculate the mean for each subgroup. This data is then written into “tidy_2.txt”

data_grp <- group_by(data, SubjectID, ActivityName)
data_avg <- summarise_each(data_grp, funs(mean))

rm(data_grp)

```

```{r}

write.table(data_avg, "tidy_2.txt", row.names = FALSE)

```



